#!/bin/bash

listrpi=(
		rpi01
		rpi02
		rpi03
 		rpi04
		rpi05
		rpi06
		rpi07
		rpi08
		rpi09
		rpi10
		rpi11
		rpi12
		rpi13
		rpi14
		rpi15
		rpi16
		rpi17
		rpi18
	)
i=1
repeat until i>18
	for i in $(listrpi); do
		ping
		if [ ping = true]; then
			echo $(listrpi) ":alive"
		else
			echo $(listrpi) ":dead"
		fi
	i= i+1
done
